name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Package Sylepsign
              run: |
                  if [ -d "Sylepsign" ]; then
                      cd Sylepsign && make pack
                      mv dist/sylepsign.tar.gz ../
                  else
                      make pack
                      mv dist/sylepsign.tar.gz ./
                  fi

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: sylepsign.tar.gz
                  generate_release_notes: true
                  draft: false
                  prerelease: false
